/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.toulouse.miage.borneclient;

import fr.toulouse.miage.borneclient.services.RMIBorneServiceManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JPanel;

/**
 *
 * @author Fanny Mnt
 */
public class BorneClient extends javax.swing.JFrame {

    private RMIBorneServiceManager manager;
    
    /**
     * Creates new form BorneClient
     */
    public BorneClient() {
        initComponents();
        this.setTitle("Borne Client");
        this.setSize(600, 700);
        try {
            this.manager = new RMIBorneServiceManager();
        } catch (NamingException ex) {
            Logger.getLogger(BorneClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login jPanLogin =new Login(this,manager);
        this.setContentPane(jPanLogin);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        BorneClient borne = new BorneClient();
        
    }

    public void changerJpanel(JPanel jAncienne, JPanel jNouvelle){
        this.remove(jAncienne);
        this.setContentPane(jNouvelle);
        this.validate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
