/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.toulouse.miage.borneclient;


import fr.toulouse.miage.borneclient.services.RMIBorneServiceManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Fanny Mnt
 */
public class BorneClient extends javax.swing.JFrame {

    private RMIBorneServiceManager manager;
    private Long idStation;
    private Long IdClient;
    private Long IdReservation;
    private String nomStation;
    private String nomUsager;
    private String prenomUsager;
    
    /**
     * Creates new form BorneClient
     */
    public BorneClient() {
        initComponents();
        this.setSize(700, 600);
        this.setTitle("Borne Client");
        
        try{
            manager = new RMIBorneServiceManager();
            SelectionStation jPanStation =new SelectionStation(this);
            this.setContentPane(jPanStation);
            this.pack();
            this.setVisible(true);
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }catch(NamingException ex){
            System.err.println("Erreur d'initialisation RMI : " + ex.getMessage());
            Logger.getLogger(BorneClient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        BorneClient borne = new BorneClient();
        
    }

    public void changerJpanel(JPanel jAncienne, JPanel jNouvelle){
        this.remove(jAncienne);
        this.setContentPane(jNouvelle);
        this.validate();
    }

    public Long getIdStation() {
        return idStation;
    }

    public void setIdStation(Long idStation) {
        this.idStation = idStation;
    }

    public Long getIdClient() {
        return IdClient;
    }

    public void setIdClient(Long IdClient) {
        this.IdClient = IdClient;
    }

    public RMIBorneServiceManager getManager() {
        return manager;
    }

    public Long getIdReservation() {
        return IdReservation;
    }

    public void setIdReservation(Long IdReservation) {
        this.IdReservation = IdReservation;
    }

    public void setNomStation(String nomStation) {
        this.nomStation = nomStation;
    }

    public String getNomStation() {
        return nomStation;
    }

    public String getNomUsager() {
        return nomUsager;
    }

    public void setNomUsager(String nomUsager) {
        this.nomUsager = nomUsager;
    }

    public String getPrenomUsager() {
        return prenomUsager;
    }

    public void setPrenomUsager(String prenomUsager) {
        this.prenomUsager = prenomUsager;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
