/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.toulouse.miage.borneclient;

import fr.miage.toulouse.spacelibshared.admin.ObjStation;
import fr.toulouse.miage.borneclient.renderer.StationRenderer;
import fr.toulouse.miage.borneclient.services.RMIBorneServiceManager;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Interface simulant la station de la borne
 * @author Fanny Mnt
 */
public class SelectionStation extends javax.swing.JPanel {

    /**
     * Jframe parente du Jpanel
     */
    public BorneClient jframeAccueil;
    /**
     * manager de la borme
     */
    private RMIBorneServiceManager manager;
    /**
     * Station sélectionné
     */
    private ObjStation selectedStation = null;
    
    /**
     * Constructeur
     * @param j jframe parente
     */
    public SelectionStation(BorneClient j) {
        initComponents();
        this.manager = j.getManager();
        this.jframeAccueil = j;
        this.initialiserListStation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSélection = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListStation = new javax.swing.JList();
        jPanelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBot = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sélectionner la station dans laquelle où vous êtes");

        jButtonSélection.setBackground(new java.awt.Color(0, 0, 51));
        jButtonSélection.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSélection.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSélection.setText("Sélectionner");
        jButtonSélection.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSélection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSélectionMouseClicked(evt);
            }
        });
        jButtonSélection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSélectionActionPerformed(evt);
            }
        });

        jListStation.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListStation);

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSélection, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonSélection, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelTop.setBackground(new java.awt.Color(0, 0, 51));
        jPanelTop.setMinimumSize(new java.awt.Dimension(168, 60));
        jPanelTop.setPreferredSize(new java.awt.Dimension(241, 90));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME to Spacelib");
        jLabel1.setToolTipText("");
        jPanelTop.add(jLabel1);

        add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelBot.setBackground(new java.awt.Color(255, 255, 255));
        add(jPanelBot, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSélectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSélectionMouseClicked
        ObjStation selectedStation = (ObjStation) jListStation.getSelectedValue();
        jframeAccueil.setNomStation(selectedStation.getNom());
        jframeAccueil.setIdStation(selectedStation.getId());
        jframeAccueil.changerJpanel(this, new Login(jframeAccueil,""));
    }//GEN-LAST:event_jButtonSélectionMouseClicked

    private void jButtonSélectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSélectionActionPerformed
        
    }//GEN-LAST:event_jButtonSélectionActionPerformed


    /**
     * Permet d'initialiser la liste des station du SI
     */
    public void initialiserListStation(){
        jListStation.removeAll();
        List<ObjStation> stations = manager.getBorneRemoteSvc().consulterStation();
        DefaultListModel modelStations = new DefaultListModel<>();
        for (ObjStation station : stations) {
            modelStations.addElement(station);
        }
        jListStation.setModel(modelStations);
        jListStation.setCellRenderer(new StationRenderer());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSélection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListStation;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
