/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.toulouse.miage.administrateurclient;

import fr.miage.toulouse.spacelibshared.admin.ObjNavette;
import fr.miage.toulouse.spacelibshared.admin.ObjQuai;
import fr.miage.toulouse.spacelibshared.admin.ObjStation;
import fr.miage.toulouse.spacelibshared.exceptions.NavetteInconnuException;
import fr.miage.toulouse.spacelibshared.exceptions.QuaiInconnuException;
import fr.toulouse.miage.administrateurclient.renderer.StationRenderer;
import fr.toulouse.miage.administrateurclient.services.RMIAdminServiceManager;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author pierreliaubet
 */
public class NewNavette extends javax.swing.JPanel {

    private JFrame main;
    
    private Home origin;
    
    private ObjStation selectedStation;
    
    private ObjQuai selectedQuai;
    
    private RMIAdminServiceManager manager;
    
    /**
     * Creates new form NewNavette
     */
    public NewNavette(JFrame main, Home origin) {
        this.main = main;
        this.origin = origin;
        try {
            manager = new RMIAdminServiceManager();
        } catch (NamingException ex) {
            Logger.getLogger(NewNavette.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        List<ObjStation> stations = manager.getAdminRemoteSvc().consulterStation();
        DefaultListModel modelSations = new DefaultListModel();
        for (ObjStation station : stations){
            modelSations.addElement(station);
        }
        listeStations.setModel(modelSations);
        listeStations.setCellRenderer(new StationRenderer());
    }
    
    private void chargerQuaiDispo(){
        List<ObjQuai> lesQuais = manager.getAdminRemoteSvc().getLesQuaisDispo(selectedStation.getId());
        DefaultListModel modelQuai = new DefaultListModel();
        for (ObjQuai quai : lesQuais){
            modelQuai.addElement(quai);
        }
        listeQuai.setModel(modelQuai);
        listeQuai.setCellRenderer(new StationRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinnerNbPlaces = new javax.swing.JSpinner();
        btnAnnuler = new javax.swing.JButton();
        btnEnregister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeStations = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeQuai = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Nouvelle navette");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Nombre de places : ");

        spinnerNbPlaces.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        btnAnnuler.setText("ANNULER");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnEnregister.setText("ENREGISTRER");
        btnEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregisterActionPerformed(evt);
            }
        });

        listeStations.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeStations.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeStationsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listeStations);

        listeQuai.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeQuai.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeQuaiValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listeQuai);

        jLabel3.setText("Arrimer à :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnAnnuler)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnregister)
                            .addComponent(spinnerNbPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spinnerNbPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnuler)
                    .addComponent(btnEnregister))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        main.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregisterActionPerformed
        ObjNavette navette = new ObjNavette();
        navette.setNbPlaces(Integer.parseInt(spinnerNbPlaces.getValue().toString()));
        if (selectedQuai != null){
            navette.setQuai(selectedQuai);
        }
        System.out.println(selectedQuai);
        try {
            manager.getAdminRemoteSvc().acheterNavette(navette);
        } catch (NavetteInconnuException ex) {
            Logger.getLogger(NewNavette.class.getName()).log(Level.SEVERE, null, ex);
        } catch (QuaiInconnuException ex) {
            Logger.getLogger(NewNavette.class.getName()).log(Level.SEVERE, null, ex);
        }
        origin.chargerDonnees();
        spinnerNbPlaces.setValue(0);
        chargerQuaiDispo();
        origin.chargerDonnees();
    }//GEN-LAST:event_btnEnregisterActionPerformed

    private void listeStationsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeStationsValueChanged
        selectedStation = (ObjStation) listeStations.getSelectedValue();
        chargerQuaiDispo();
    }//GEN-LAST:event_listeStationsValueChanged

    private void listeQuaiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeQuaiValueChanged
        selectedQuai = (ObjQuai) listeQuai.getSelectedValue();
    }//GEN-LAST:event_listeQuaiValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listeQuai;
    private javax.swing.JList listeStations;
    private javax.swing.JSpinner spinnerNbPlaces;
    // End of variables declaration//GEN-END:variables
}
